runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app

- url: /index\.html
  script: main.app

- url: /(.*)
  static_files: static_files/\1
  upload: ./static_files/(.*)


- url: /admin/.*
  script: admin.app
  login: admin

- url: /.*
  script: not_found.app
